name = "riindu-moment"
compatibility_date = "2026-01-05"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"
[observability]
enabled = true

[assets]
directory = "./assets"
binding = "ASSETS"